# A string used to distinguish different Supabase projects on the same host
project_id = "portfolio-site"

[api]
enabled = true
# Port to use for the API URL
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API endpoints
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request
extra_search_path = ["public", "extensions"]
# The maximum number of rows returns from a table in a single request
max_rows = 1000

[db]
# Port to use for the local database URL
port = 54322
# The database major version to use
major_version = 15

[db.pooler]
enabled = false
# Port to use for pooler
port = 54329
# Pooler mode: "transaction", "session"
default_pool_size = 20
max_client_conn = 100

[realtime]
# Enable the Realtime API
enabled = true
# Bind realtime via either IPv4 or IPv6
ip_version = "IPv4"

[studio]
enabled = true
# Port to use for Supabase Studio
port = 54323
# External URL of the API server that frontend connects to
api_url = "http://127.0.0.1:54321"
# OpenAI API Key to use for Supabase AI in the Supabase Studio
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
# Enable inbucket for email testing
enabled = true
# Port to use for the email testing server web interface
port = 54324
# Smtp server host to use for sending emails
smtp_port = 54325
# Web server host to use for viewing emails
pop3_port = 54326

[storage]
enabled = true
# The maximum file size allowed (e.g. "5MB", "500KB")
file_size_limit = "50MiB"

[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects
site_url = "http://localhost:1313"
# A list of *exact* URLs that auth providers are permitted to redirect to
additional_redirect_urls = ["https://localhost:1313"]
# How long tokens are valid for, in seconds
jwt_expiry = 3600
# If disabled, the refresh token will never expire
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry
refresh_token_reuse_interval = 10
# Allow/disallow new user signups
enable_signup = true
# Allow/disallow testing manual linking of accounts
enable_manual_linking = false

[auth.email]
# Allow/disallow new user signups via email to your project
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old and new email addresses
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in
enable_confirmations = false
# Controls the minimum amount of time that must pass before sending a second confirmation or password reset email
max_frequency = "1s"

# Use an external OAuth provider
[auth.external.apple]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl
redirect_uri = ""
# Overrides the default auth provider URL
url = ""

[analytics]
enabled = false
port = 54327
vector_port = 9001