baseURL: https://vocal-pony-24e3de.netlify.app/
title: Brandon JP Lambert
languageCode: en-us
defaultContentLanguage: en

# Output
enableRobotsTXT: true
enableGitInfo: false

# Taxonomies
taxonomies:
  tag: tags
  category: categories

# Permalinks
permalinks:
  make: /:section/:slug/
  learn: /:section/:slug/
  think: /:section/:slug/
  meet: /:section/:slug/
