en:
  languageName: English
  weight: 1
  params:
    dateformat: January 2, 2006
    description: Creator working at the intersection of technology and art
    
es:
  languageName: Español
  weight: 2
  params:
    dateformat: 2 de January de 2006
    description: Creador trabajando en la intersección de tecnología y arte
