main:
  - name: Letratos
    url: /poetry/
    weight: 10
    title: "Photography & Poetry"
  - name: Teaching & Learning
    url: /teaching-learning/
    weight: 20
  - name: Me
    url: /me/
    weight: 30