main:
  - name: Writing
    url: /writing/
    weight: 10
  - name: Learn
    url: /learn/
    weight: 20
  - name: Think
    url: /think/
    weight: 30
  - name: Meet
    url: /meet/
    weight: 40
