main:
  - name: Writing
    url: /writing/
    weight: 10
  - name: Tools
    url: /tools/
    weight: 20
  - name: Think
    url: /think/
    weight: 30
  - name: Meet
    url: /meet/
    weight: 40
