main:
  - name: Poetry
    url: https://www.letratos.com
    weight: 10
  - name: Tools
    url: /tools/
    weight: 20
  - name: Photography
    url: /photography/
    weight: 30
  - name: Me
    url: /me/
    weight: 40