main:
  - name: Letratos
    url: /es/photography/
    weight: 10
    title: "Fotografía y Poesía"
  - name: Enseñanza y Aprendizaje
    url: /es/aprender/
    weight: 20
  - name: Yo
    url: /es/me/
    weight: 30