main:
  - name: Escribir
    url: /es/escribir/
    weight: 10
  - name: Aprender
    url: /es/learn/
    weight: 20
  - name: Pensar
    url: /es/think/
    weight: 30
  - name: Conocer
    url: /es/meet/
    weight: 40