author: Brandon JP Lambert
description: Fourth-generation educator with MA-TESOL and 10 years in language education and edtech
email: contact@brandonjplambert.com

features:
  darkMode: true
  search: true

social:
  github: https://github.com/yourusername
  twitter: https://twitter.com/yourusername
  linkedin: https://linkedin.com/in/brandonjplambert
