author: Your Name
description: Creator working at the intersection of technology and art
email: your.email@example.com

features:
  darkMode: true
  search: true

social:
  github: https://github.com/yourusername
  twitter: https://twitter.com/yourusername
