baseURL: "http://localhost:1313/"
defaultContentLanguage: "en"
title: "Portfolio"
# theme: "your-theme-name"  # No theme - using custom layouts

languages:
  en:
    languageName: "English"
    languageCode: "en-US"
    weight: 1
    title: "Portfolio"
  es:
    languageName: "Español"
    languageCode: "es-ES"
    weight: 2
    title: "Portafolio"

menu:
  main:
    - name: "Make"
      url: "/make/"
      weight: 10
    - name: "Learn"
      url: "/learn/"
      weight: 20
    - name: "Think"
      url: "/think/"
      weight: 30
    - name: "Meet"
      url: "/meet/"
      weight: 40

params:
  description: "My Portfolio Site"
  author: "Your Name"
