baseURL: "https://vocal-pony-24e3de.netlify.app/"
defaultContentLanguage: "en"
title: "Brandon JP Lambert"
# theme: "your-theme-name"  # No theme - using custom layouts

languages:
  en:
    languageName: "English"
    languageCode: "en-US"
    weight: 1
    title: "Brandon JP Lambert"
  es:
    languageName: "Español"
    languageCode: "es-ES"
    weight: 2
    title: "Brandon JP Lambert"

menu:
  main:
    - name: "Letratos"
      url: "/photography/"
      weight: 10
      title: "Photography & Poetry"
    - name: "Teaching & Learning"
      url: "/teaching-learning/"
      weight: 20
    - name: "Me"
      url: "/me/"
      weight: 30

params:
  description: "Professional portfolio showcasing web development, design, and creative projects"
  author: "Brandon JP Lambert"
  keywords: ["portfolio", "web development", "design", "programming", "creative", "full stack"]
  og_image: "/images/og-default.jpg"
  twitter_username: ""
  logo: "/images/logo.png"
  social:
    linkedin: "https://linkedin.com/in/brandonjplambert"
    github: "https://github.com/bjpl"
    email: "contact@brandonjplambert.com"

# SEO and Analytics
googleAnalytics: "G-PLACEHOLDER123"  # Replace with your actual GA tracking ID
enableRobotsTXT: true
sitemap:
  changefreq: "weekly"
  priority: 0.5
  filename: "sitemap.xml"

# Asset optimization
imageProcessing:
  cover:
    resampleFilter: "CatmullRom"
    quality: 85
    anchor: "smart"
  fill:
    resampleFilter: "CatmullRom"
    quality: 85
    anchor: "smart"

# Resource hints
services:
  preload:
    enable: true
  prefetch:
    enable: true
  dns-prefetch:
    enable: true

# Performance Optimization
minify:
  minifyOutput: true
  # Advanced minification settings
  disableHTML: false
  disableCSS: false
  disableJS: false
  disableJSON: false
  disableSVG: false
  disableXML: false
  tdewolff:
    html:
      keepDocumentTags: false
      keepEndTags: false
      keepQuotes: false
      keepWhitespace: false
    css:
      precision: 0
    js:
      version: 2022
    json:
      precision: 0
    svg:
      precision: 1
    xml:
      keepWhitespace: false

# Build Performance
build:
  noJSConfigInAssets: true
  useResourceCacheWhen: "fallback"
  writeStats: true

# Caching Configuration
caches:
  assets:
    dir: ":cacheDir/:project"
    maxAge: "10000h"
  getcsv:
    maxAge: "10s"
  getjson:
    maxAge: "10s"
  getresource:
    maxAge: "10s"
  images:
    dir: ":cacheDir/:project"
    maxAge: "10000h"
  modules:
    dir: ":cacheDir/modules"
    maxAge: "10000h"

# Processing optimization
processing:
  images:
    quality: 85
    resampleFilter: "Lanczos"
    anchor: "Smart"
  css:
    postcss:
      enable: true
  js:
    target: "es2018"

# Markdown rendering
markup:
  goldmark:
    renderer:
      unsafe: true

# RSS
outputs:
  home: ["HTML", "RSS", "JSON"]
  section: ["HTML", "RSS"]
