baseURL: "http://localhost:1313/"
defaultContentLanguage: "en"
title: "Portfolio"
# theme: "your-theme-name"  # No theme - using custom layouts

languages:
  en:
    languageName: "English"
    languageCode: "en-US"
    weight: 1
    title: "Portfolio"
  es:
    languageName: "Español"
    languageCode: "es-ES"
    weight: 2
    title: "Portafolio"

menu:
  main:
    - name: "Make"
      url: "/make/"
      weight: 10
    - name: "Learn"
      url: "/learn/"
      weight: 20
    - name: "Think"
      url: "/think/"
      weight: 30
    - name: "Meet"
      url: "/meet/"
      weight: 40

params:
  description: "Professional portfolio showcasing web development, design, and creative projects"
  author: "Brandon Lambert"
  keywords: ["portfolio", "web development", "design", "programming", "creative", "full stack"]
  og_image: "/images/og-default.jpg"
  twitter_username: ""
  logo: "/images/logo.png"

# SEO and Analytics
googleAnalytics: ""  # Add your GA tracking ID here (e.g., "G-XXXXXXXXXX")
enableRobotsTXT: true
sitemap:
  changefreq: "weekly"
  priority: 0.5

# Performance
minify:
  minifyOutput: true

# RSS
outputs:
  home: ["HTML", "RSS", "JSON"]
  section: ["HTML", "RSS"]
