baseURL: "https://vocal-pony-24e3de.netlify.app/"
defaultContentLanguage: "en"
title: "Brandon JP Lambert"
# theme: "your-theme-name"  # No theme - using custom layouts

languages:
  en:
    languageName: "English"
    languageCode: "en-US"
    weight: 1
    title: "Brandon JP Lambert"
  es:
    languageName: "Español"
    languageCode: "es-ES"
    weight: 2
    title: "Brandon JP Lambert"

menu:
  main:
    - name: "Letratos"
      url: "/photography/"
      weight: 10
      title: "Photography & Poetry"
    - name: "Teaching & Learning"
      url: "/teaching-learning/"
      weight: 20
    - name: "Me"
      url: "/me/"
      weight: 30

params:
  description: "Professional portfolio showcasing web development, design, and creative projects"
  author: "Brandon JP Lambert"
  keywords: ["portfolio", "web development", "design", "programming", "creative", "full stack"]
  og_image: "/images/og-default.jpg"
  twitter_username: ""
  logo: "/images/logo.png"
  social:
    linkedin: "https://linkedin.com/in/brandonjplambert"
    github: "https://github.com/bjpl"
    email: "contact@brandonjplambert.com"

# SEO and Analytics
googleAnalytics: "G-PLACEHOLDER123"  # Replace with your actual GA tracking ID
enableRobotsTXT: true
sitemap:
  changefreq: "weekly"
  priority: 0.5

# Performance
minify:
  minifyOutput: true

# Markdown rendering
markup:
  goldmark:
    renderer:
      unsafe: true

# RSS
outputs:
  home: ["HTML", "RSS", "JSON"]
  section: ["HTML", "RSS"]
