[build]
  # Simple static site build (Next.js with output: 'export' automatically exports)
  command = "npm run build"
  publish = "out"
  base = "."
  
  # Node.js version
  [build.environment]
    NODE_VERSION = "18"
    NPM_FLAGS = "--no-optional"
    NEXT_TELEMETRY_DISABLED = "1"

# Legacy URL redirects
[[redirects]]
  from = "/admin"
  to = "/admin/dashboard"
  status = 301

[[redirects]]
  from = "/make/*"
  to = "/writing/:splat"
  status = 301
  
[[redirects]]
  from = "/learn/*"
  to = "/tools/:splat"
  status = 301
  
[[redirects]]
  from = "/teaching-learning/*"
  to = "/teaching/:splat"
  status = 301

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Static assets caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"