[build]
  # Next.js build configuration
  command = "npm run build"
  publish = ".next"
  base = "."
  
  # Node.js version
  [build.environment]
    NODE_VERSION = "18"
    NPM_FLAGS = "--no-optional"
    NEXT_TELEMETRY_DISABLED = "1"

# Next.js specific configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirects for Next.js App Router
[[redirects]]
  from = "/admin"
  to = "/admin/dashboard"
  status = 301
  
[[redirects]]
  from = "/admin/"
  to = "/admin/dashboard"
  status = 301

# Legacy Hugo URL redirects
[[redirects]]
  from = "/make/*"
  to = "/writing/:splat"
  status = 301
  
[[redirects]]
  from = "/learn/*"
  to = "/tools/:splat"
  status = 301
  
[[redirects]]
  from = "/teaching-learning/*"
  to = "/teaching/:splat"
  status = 301

# API routes - Disabled for static site
# [[redirects]]
#   from = "/api/health"
#   to = "/.netlify/functions/health"
#   status = 200
# 
# [[redirects]]
#   from = "/api/contact"
#   to = "/.netlify/functions/contact"
#   status = 200

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=31536000, immutable"

# Static assets caching
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML caching
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Functions configuration - Disabled for static portfolio site
# Commenting out functions to avoid deployment issues
# [functions]
#   directory = "netlify/functions"
#   node_bundler = "esbuild"