[build]
  command = "hugo --minify --cleanDestinationDir --verbose"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.121.0"
  HUGO_ENV = "production"
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

# Legacy URL redirects for old navigation
[[redirects]]
  from = "/learn/*"
  to = "/tools/:splat"
  status = 301

[[redirects]]
  from = "/make/*"
  to = "/writing/:splat"
  status = 301

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"