[build]
  command = "rm -rf public && hugo --minify --cleanDestinationDir --gc"
  publish = "public"
  base = ""

[build.environment]
  HUGO_VERSION = "0.121.0"
  HUGO_ENV = "production"
  NODE_VERSION = "18"
  GO_VERSION = "1.21"
  BUILD_ID = "2025-08-21-v3-force-clear"
  VITE_API_URL = "/api"
  VITE_SITE_URL = "https://vocal-pony-24e3de.netlify.app"
  
[context.production]
  command = "rm -rf public && hugo --minify --cleanDestinationDir --gc"
  
[context.branch-deploy]
  command = "rm -rf public && hugo --minify --cleanDestinationDir --gc"

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; connect-src 'self' https:; font-src 'self' data: https:;"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"

# CSS caching with proper versioning
[[headers]]
  for = "/css/main.css"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"
    ETag = "true"

[[headers]]
  for = "/css/links-unified.css"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"
    ETag = "true"

# Asset Optimization
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Page Speed Optimization - Removed incorrect preloads

# API Proxy Rules for Backend Integration
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.netlify.app/.netlify/functions/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

# Domain Redirects
[[redirects]]
  from = "https://vocal-pony-24e3de.netlify.app/*"
  to = "https://vocal-pony-24e3de.netlify.app/:splat"
  status = 301
  force = true

# Legacy URL Redirects
[[redirects]]
  from = "/learn/*"
  to = "/tools/:splat"
  status = 301

[[redirects]]
  from = "/make/*"
  to = "/writing/:splat"
  status = 301

# Function Configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Build Plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

  [plugins.inputs]
    baseUrl = "https://vocal-pony-24e3de.netlify.app"
    sitemapPath = "/sitemap.xml"

# Development Settings
[dev]
  framework = "hugo"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false