apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portfolio-uploads-pvc
  namespace: portfolio-backend
  labels:
    app: portfolio-backend
    component: storage
    type: uploads
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portfolio-logs-pvc
  namespace: portfolio-backend
  labels:
    app: portfolio-backend
    component: storage
    type: logs
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  namespace: portfolio-backend
  labels:
    app: postgres
    component: storage
    type: database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
  namespace: portfolio-backend
  labels:
    app: redis
    component: storage
    type: cache
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd