# Prometheus alerting rules for portfolio site
groups:
  - name: portfolio.rules
    interval: 30s
    rules:
      # Application availability
      - alert: PortfolioAppDown
        expr: up{job="portfolio-app"} == 0
        for: 1m
        labels:
          severity: critical
          service: portfolio-app
        annotations:
          summary: "Portfolio application is down"
          description: "Portfolio application has been down for more than 1 minute"

      # High response time
      - alert: HighResponseTime
        expr: rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m]) > 2
        for: 5m
        labels:
          severity: warning
          service: portfolio-app
        annotations:
          summary: "High response time detected"
          description: "Average response time is {{ $value }}s"

      # High error rate
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) * 100 > 5
        for: 2m
        labels:
          severity: critical
          service: portfolio-app
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }}%"

      # Memory usage
      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes / 1024 / 1024 > 500
        for: 5m
        labels:
          severity: warning
          service: portfolio-app
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value }}MB"

      # CPU usage
      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
          service: portfolio-app
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}%"

      # Database connectivity
      - alert: DatabaseDown
        expr: up{job="postgres-exporter"} == 0
        for: 1m
        labels:
          severity: critical
          service: database
        annotations:
          summary: "Database is down"
          description: "PostgreSQL database is not responding"

      # Redis connectivity
      - alert: RedisDown
        expr: up{job="redis-exporter"} == 0
        for: 1m
        labels:
          severity: critical
          service: redis
        annotations:
          summary: "Redis is down"
          description: "Redis cache is not responding"

      # Disk space
      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100 < 20
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "Low disk space"
          description: "Disk space is {{ $value }}% full"

      # SSL certificate expiration
      - alert: SSLCertificateExpiring
        expr: probe_ssl_earliest_cert_expiry - time() < 604800
        for: 1m
        labels:
          severity: warning
          service: ssl
        annotations:
          summary: "SSL certificate expiring soon"
          description: "SSL certificate expires in {{ $value | humanizeDuration }}"

      # Backup failures
      - alert: BackupFailed
        expr: increase(backup_failures_total[1h]) > 0
        for: 1m
        labels:
          severity: critical
          service: backup
        annotations:
          summary: "Backup failed"
          description: "Database backup has failed"