[build]
builder = "NIXPACKS"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Environment Variables
[env]
NODE_ENV = "production"
PORT = "3333"
HOST = "0.0.0.0"

# Build configuration
[build.env]
NODE_VERSION = "18"
NPM_CONFIG_PRODUCTION = "false"

# Deployment settings
[deploy.env]
NODE_OPTIONS = "--max-old-space-size=1024"

# Health check configuration
[deploy.healthcheck]
path = "/api/health"
timeout = 30
interval = 60

# Resource limits
[deploy.resources]
cpu = "1000m"
memory = "1024Mi"

# Scaling configuration
[deploy.autoscaling]
enabled = true
minReplicas = 1
maxReplicas = 5
targetCPUUtilization = 70
targetMemoryUtilization = 80

# Service configuration
[deploy.networking]
serviceName = "portfolio-backend"
servicePort = 3333