services:
  - type: web
    name: portfolio-backend
    runtime: node
    region: oregon
    plan: starter
    buildCommand: cd backend && npm ci --prefer-offline && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3333
      - key: HOST
        value: 0.0.0.0
      - key: DB_HOST
        fromDatabase:
          name: portfolio-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: portfolio-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: portfolio-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: portfolio-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: portfolio-db
          property: password
      - key: REDIS_HOST
        fromService:
          name: portfolio-redis
          type: redis
          property: host
      - key: REDIS_PORT
        fromService:
          name: portfolio-redis
          type: redis
          property: port
      - key: REDIS_PASSWORD
        fromService:
          name: portfolio-redis
          type: redis
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://portfolio.yourdomain.com
    healthCheckPath: /api/health
    autoDeploy: true
    
  - type: redis
    name: portfolio-redis
    region: oregon
    plan: starter
    maxmemoryPolicy: allkeys-lru

databases:
  - name: portfolio-db
    region: oregon
    plan: starter
    databaseName: portfolio_production
    user: portfolio_user