# Hugo Build Optimization Configuration
# This file contains advanced build performance settings

[build]
  # Build performance settings
  noJSConfigInAssets = true
  useResourceCacheWhen = "fallback"
  writeStats = true
  buildStats = true

[caches]
  # Asset caching configuration
  [caches.assets]
    dir = ":cacheDir/:project/assets"
    maxAge = "10000h"
  
  [caches.images]
    dir = ":cacheDir/:project/images"
    maxAge = "10000h"
    
  [caches.modules]
    dir = ":cacheDir/modules"
    maxAge = "10000h"
    
  [caches.getresource]
    maxAge = "1h"
    
  [caches.getjson]
    maxAge = "1h"
    
  [caches.getcsv]
    maxAge = "1h"

[processing]
  # Image processing optimization
  [processing.images]
    quality = 85
    resampleFilter = "Lanczos"
    anchor = "Smart"
    hint = "photo"
    
  # CSS processing
  [processing.css]
    [processing.css.postcss]
      enable = true
      use = "autoprefixer"
      
  # JavaScript processing  
  [processing.js]
    target = "es2018"
    
# Minification settings
[minify]
  minifyOutput = true
  disableHTML = false
  disableCSS = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepDocumentTags = false
      keepEndTags = false
      keepQuotes = false
      keepWhitespace = false
      
    [minify.tdewolff.css]
      precision = 0
      keepCSS2 = false
      
    [minify.tdewolff.js]
      version = 2022
      keepVarNames = false
      precision = 0
      
    [minify.tdewolff.json]
      precision = 0
      keepNumbers = false
      
    [minify.tdewolff.svg]
      precision = 1
      
    [minify.tdewolff.xml]
      keepWhitespace = false

# Output formats optimization
[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss+xml"
    baseName = "index"
    isPlainText = false
    rel = "alternate"
    
  [outputFormats.JSON]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true

# Taxonomy optimization
[taxonomies]
  category = "categories"
  tag = "tags"
  skill = "skills"
  
# Security settings for build
[security]
  [security.exec]
    allow = ["^(dart-)?sass(-embedded)?$", "^go$", "^npx$", "^postcss$"]
    osEnv = ["(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG)$"]
  
  [security.funcs]
    getenv = ["^HUGO_", "^CI$"]
    
  [security.http]
    methods = ["(?i)GET|POST"]
    urls = [".*"]

# Related content optimization
[related]
  includeNewer = true
  threshold = 80
  toLower = true
  
  [[related.indices]]
    name = "keywords"
    weight = 100
    
  [[related.indices]]
    name = "tags"
    weight = 80
    
  [[related.indices]]
    name = "categories" 
    weight = 60

# Server configuration for development
[server]
  [[server.headers]]
    for = "/**"
    [server.headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      X-Content-Type-Options = "nosniff"
      Referrer-Policy = "strict-origin-when-cross-origin"